### PR TITLE
Fix/mobile format

### PR DESCRIPTION
**Pull request by Y-Negash**
This pr closes issue #23, the buttons were too big for certain screen sizes causing the container to overflow. The media queries fix this. It currently fixes the problem for screens bigger than 320px.

### CODE REVIEW

**Comment by Aebel-Shajan** [comment]
I resolved the the merge conflicts with main. uhhh i just realised that i brought in the back button from main, idk how this will affect the css.

**Comment by Aebel-Shajan** [comment]
Im sorry 😭I broke it

**Review by Aebel-Shajan — APPROVED** [review]

**Comment by Y-Negash** [comment]
THanks a lot aebel, I fixed it again 😂

**Comment by Y-Negash** [comment]
wait I forgot to change the button size so it doesn't shrink weirdly on mobile!

**Comment by Y-Negash** [comment]
okay now I'm done

**Pull request merged**
