### PR TITLE
added a AboutUs page

### PR DESCRIPTION
**Pull request by KajananGit**
I have added a About Us page. More info can and will be added to the page. 
The link to the page can be found in the footer on the home page.

PS: I know that the styling is horrific. I will improve on this.

### CODE REVIEW

**Review by Aebel-Shajan — APPROVED** [review]
Looks good, the description is really well written. Did you use chatgpt lol

**Comment by KajananGit** [comment]
Yh I just pasted a brief description into ChatGPT and it did the rest for me

**Review by Y-Negash — CHANGES_REQUESTED** [review]
Looks great! I would probably suggest putting About Us right at the top instead of the footer. Since it's quite important, it should be in a easy to find place.  We can put a contact us section in the footer instead?

**Comment by KajananGit** [comment]
Yep agree. Should I create a navbar or something in that direction? 
It would also eliminate the need to have the back-button.

**Comment by Aebel-Shajan** [comment]
Yeah i think the navigation component is still here.

**Review by Y-Negash — APPROVED** [review]

**Pull request merged**
